version: "3.8"

services:
  jenkins:
    image: matheushenriquefonsecaafonso/jenkins-custom:v1.0
    container_name: jenkins-container-2
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - pipeline_network

  postgres:
    image: postgres:15
    container_name: postgres-container-2
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - pipeline_network
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  pipeline_network:

volumes:
  jenkins_home:
