# Using the official Jenkins LTS image
FROM jenkins/jenkins:lts

# root mode to install dependencies
USER root

# copy the plugins.txt file to the Jenkins home directory
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

# Install plugins listed in plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

# Update the package list and install Docker, Python 3.11, and other dependencies
RUN apt-get update && apt-get install -y \
    docker.io \
    python3 \
    python3-pip \
    python3.11 \
    python3.11-distutils \
    python3.11-venv \
    git \
    curl \
    unzip \
    postgresql-client \
    && apt-get clean

# Create a symbolic link for python3.11
RUN python3.11 -m venv /opt/venv

# Activate the virtual environment
RUN /opt/venv/bin/pip install --upgrade pip

# Instalar o pip e o virtualenv no ambiente virtual
RUN /opt/venv/bin/pip install pytest coverage

# Define the working directory
ENV PATH="/opt/venv/bin:$PATH"

# Add the Jenkins user to the Docker group
RUN mkdir -p /var/jenkins_home/casc_configs

# Configuration as Code (CasC) plugin
COPY casc.yaml /var/jenkins_home/casc_configs/

# Configure jenkins to use the CasC configuration
ENV CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs

# back to jenkins user
USER jenkins

# port 8080 is the default Jenkins port
EXPOSE 8080

# port 50000 is the default Jenkins agent port
EXPOSE 50000